version: "3.3"

services:
  nginx:
    container_name: nginx
    build:
      context: ./components/nginx
      args:
        - NGINX_VERSION=${NGINX_VERSION}
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - ./components/nginx/conf.d/default.conf:/etc/nginx/default.conf
      - ./components/nginx/conf.d:/etc/nginx/conf.d
      - ${WEB_ROOT_PATH}:/var/www
      - ${WEB_LOGS}:/var/logs
  php:
    container_name: php
    build:
      context: ./components/php
      args:
        - PHP_VERSION=${PHP_VERSION}
        - INSTALL_REDIS=${INSTALL_REDIS}
        - REDIS_VERSION=${REDIS_VERSION}
        - INSTALL_SWOOLE=${INSTALL_SWOOLE}
        - SWOOLE_VERSION=${SWOOLE_VERSION}
        - INSTALL_PCNTL=${INSTALL_PCNTL}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
        - XDEBUG_VERSION=${XDEBUG_VERSION}
    ports:
      - "9000:9000"
      - "8080:8080"
      - "9501:9501"
    volumes:
      - ./components/php/${PHP_VERSION}/php.ini:/usr/local/etc/php/php.ini
      - ./components/php/${PHP_VERSION}/www.conf:/usr/local/etc/php/php-fpm.d/www.conf
      - ${WEB_ROOT_PATH}:/var/www
  mysql:
    container_name: mysql
    build:
      context: ./components/mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./components/mysql/mysql.cnf:/etc/mysql/conf.d/my.cnf
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

