version: "3.3"

services:
  nginx:
    container_name: nginx
    build:
      context: ./components/nginx
      args:
        - NGINX_VERSION=${NGINX_VERSION}
        - INSTALL_COMPOSER=${INSTALL_COMPOSER}
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - ./components/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./components/nginx/conf.d:/etc/nginx/conf.d
      - ${WEB_ROOT_PATH}:/var/www
  php:
    container_name: php
    build:
      context: ./components/php
      args:
        - PHP_VERSION=${PHP_VERSION}
    ports:
      - "9000:9000"
    volumes:
      - ./components/php/${PHP_VERSION}/php.ini:/usr/local/etc/php/php.ini
      - ./components/php/${PHP_VERSION}/www.conf:/usr/local/etc/php/php-fpm.d/www.conf
      - ${WEB_ROOT_PATH}:/var/www

