version: "3.3"

services:
  nginx:
    container_name: nginx
    build:
      context: ./components/nginx
      args:
        - NGINX_VERSION=${NGINX_VERSION}
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - ./components/nginx/conf.d/default.conf:/etc/nginx/default.conf
      - ./components/nginx/conf.d:/etc/nginx/conf.d
      - ${WEB_ROOT_PATH}:/var/www
      - ${WEB_LOGS}:/var/logs
  php:
    container_name: php
    build:
      context: ./components/php
      args:
        - PHP_VERSION=${PHP_VERSION}
        - INSTALL_REDIS=${INSTALL_REDIS}
        - REDIS_VERSION=${REDIS_VERSION}
        - INSTALL_SWOOLE=${INSTALL_SWOOLE}
        - SWOOLE_VERSION=${SWOOLE_VERSION}
        - INSTALL_PCNTL=${INSTALL_PCNTL}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
        - XDEBUG_VERSION=${XDEBUG_VERSION}
    ports:
      - "9000:9000"
      - "8080:8080"
    volumes:
      - ./components/php/${PHP_VERSION}/php.ini:/usr/local/etc/php/php.ini
      - ./components/php/${PHP_VERSION}/www.conf:/usr/local/etc/php/php-fpm.d/www.conf
      - ${WEB_ROOT_PATH}:/var/www

